//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverageProgram.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AverageProgram.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Avert1 {
            get {
                return ResourceManager.GetString("Avert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a subject name..
        /// </summary>
        internal static string Expt1 {
            get {
                return ResourceManager.GetString("Expt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a positive number between 0.1 and 5.0 for credit..
        /// </summary>
        internal static string Expt2 {
            get {
                return ResourceManager.GetString("Expt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 0 and 100 for average (No decimals, text, symbols, etc)..
        /// </summary>
        internal static string Expt3 {
            get {
                return ResourceManager.GetString("Expt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be empty..
        /// </summary>
        internal static string Expt4 {
            get {
                return ResourceManager.GetString("Expt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a format from the dropdown menu..
        /// </summary>
        internal static string Expt5 {
            get {
                return ResourceManager.GetString("Expt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject has been added..
        /// </summary>
        internal static string Expt6 {
            get {
                return ResourceManager.GetString("Expt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string StringAdd {
            get {
                return ResourceManager.GetString("StringAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subject.
        /// </summary>
        internal static string StringAddSub {
            get {
                return ResourceManager.GetString("StringAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string StringAverage {
            get {
                return ResourceManager.GetString("StringAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string StringCredit {
            get {
                return ResourceManager.GetString("StringCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subject.
        /// </summary>
        internal static string StringEditSub {
            get {
                return ResourceManager.GetString("StringEditSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter average.
        /// </summary>
        internal static string StringEnterAverage {
            get {
                return ResourceManager.GetString("StringEnterAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter credit.
        /// </summary>
        internal static string StringEnterCredit {
            get {
                return ResourceManager.GetString("StringEnterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter file name.
        /// </summary>
        internal static string StringEnterFileName {
            get {
                return ResourceManager.GetString("StringEnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter name.
        /// </summary>
        internal static string StringEnterName {
            get {
                return ResourceManager.GetString("StringEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string StringExport {
            get {
                return ResourceManager.GetString("StringExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string StringFileName {
            get {
                return ResourceManager.GetString("StringFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string StringFormat {
            get {
                return ResourceManager.GetString("StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string StringGrade {
            get {
                return ResourceManager.GetString("StringGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string StringLanguage {
            get {
                return ResourceManager.GetString("StringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string StringResults {
            get {
                return ResourceManager.GetString("StringResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string StringSubject {
            get {
                return ResourceManager.GetString("StringSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unweighted average:.
        /// </summary>
        internal static string StringUA {
            get {
                return ResourceManager.GetString("StringUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string StringUpdate {
            get {
                return ResourceManager.GetString("StringUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Subject.
        /// </summary>
        internal static string StringUpdateSub {
            get {
                return ResourceManager.GetString("StringUpdateSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string StringUserEnterName {
            get {
                return ResourceManager.GetString("StringUserEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted average:.
        /// </summary>
        internal static string StringWA {
            get {
                return ResourceManager.GetString("StringWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subject:.
        /// </summary>
        internal static string StringYourSub {
            get {
                return ResourceManager.GetString("StringYourSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been exported successfully.
        /// </summary>
        internal static string Success1 {
            get {
                return ResourceManager.GetString("Success1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been exported successfully to:.
        /// </summary>
        internal static string Success2 {
            get {
                return ResourceManager.GetString("Success2", resourceCulture);
            }
        }
    }
}
